### ISSUE TITLE
Decide on a name for `requestPictureInPicture` for v2

### ISSUE THREAD

**Issue by beccahughes** [w3c/picture-in-picture#129]
The new `requestPictureInPicture` API has different parameters and a different algorithm so we should consider renaming it. 

`copyToPictureInPictureWindow` was proposed however this has problems if we called it once and then had the window open and we called it again on a different element we should reset the Picture-in-Picture window before we copy the new element.

**Comment by beaufortfrancois** [comment]
Closing all [v2](https://github.com/w3c/picture-in-picture/labels/v2) labels issues as this is replaced by the dedicated [WICG Document Picture-in-Picture API](https://github.com/WICG/document-picture-in-picture) proposal.
