### ISSUE TITLE
Feature detection for v2

### ISSUE THREAD

**Issue by beccahughes** [w3c/picture-in-picture#139]
We should have a way beyond `pictureInPictureEnabled` for a website to check whether picture in picture is supported. For example, a site may not wish to show UI if the user agent does not support interactive PIP.

**Comment by pliu6** [comment]
Could you clarify the requirement? Are you suggesting something like `pictureInPictureSupported`?

**Comment by beaufortfrancois** [comment]
Closing all [v2](https://github.com/w3c/picture-in-picture/labels/v2) labels issues as this is replaced by the dedicated [WICG Document Picture-in-Picture API](https://github.com/WICG/document-picture-in-picture) proposal.
