### ISSUE TITLE
Need a way to detect input limitations

### ISSUE THREAD

**Issue by beccahughes** [w3c/picture-in-picture#143]
Interactive arbitrary content will have limited keyboard input allowed. Developers should have a a way to detect this. In development this could be a console message.

**Comment by beaufortfrancois** [comment]
Closing all [v2](https://github.com/w3c/picture-in-picture/labels/v2) labels issues as this is replaced by the dedicated [WICG Document Picture-in-Picture API](https://github.com/WICG/document-picture-in-picture) proposal.
