### ISSUE TITLE
disablePictureInPicture should initialize to false

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/picture-in-picture#144]
Spec says:

> 5. OPTIONALLY, if the {{disablePictureInPicture}} attribute is present on |video|, throw an {{InvalidStateError}} and abort these steps.

I think here you want to check the value of the IDL attribute value, no? It would be weird if the `disablePictureInPicture` conditionally appeared and disappeared. 

What is confusing here is that the specs seems to be talking about the HTML attribute itself being present... but what matters more (or what is easier to check) is the value being reflected in the IDL attribute (so maybe just initialize it to false).

**Comment by beaufortfrancois** [comment]
How would you rephrase it?
We do have this line. Is it not enough?

> The disablePictureInPicture IDL attribute MUST reflect the content attribute of the same name.

**Comment by beaufortfrancois** [comment]
@marcoscaceres  I'm still not sure what you meant. Shall I explicitly add `IDL` before attribute to avoid confusion?

_OPTIONALLY, if the {{disablePictureInPicture}} **IDL** attribute is present on |video|, throw an {{InvalidStateError}} and abort these steps._
