### ISSUE TITLE
EnterPictureInPictureEvent should maybe just be PictureInPictureEvent?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/picture-in-picture#145]
Seems a bit weird to have "Enter" at the front of `EnterPictureInPictureEvent`... why not just generalize it to "PictureInPictureEvent"?

**Comment by beaufortfrancois** [comment]
There are other Picture-in-Picture events such as `Leave` and `Resize`.
This is why the event for entering Picture-in-Picture is prefixed with `Enter`.

**Comment by marcoscaceres** [comment]
Couldn't we use just one tho? And then just use the type to say what it is for?

**Comment by beaufortfrancois** [comment]
The `EnterPictureInPictureEvent` constructor event requires a `PictureInPictureWindow` while others actually don't. Having a generic `PictureInPictureEvent` that would not apply to `leavepictureinpicture` seems weird.

 I'm gonna close this issue but let me know if you feel strongly about it and I'll re-open for further discussion.

**Comment by foolip** [comment]
I found this issue while trying to figure out what happened with `EnterPictureInPictureEvent`, which is currently shipping in Safari 14. Turns out the renaming did happen the day after this issue was closed in https://github.com/w3c/picture-in-picture/pull/189.

**Comment by beaufortfrancois** [comment]
@pliu6 should be able to help with that.
It seems like a simple rename would work for https://github.com/WebKit/WebKit/blob/main/Source/WebCore/Modules/pictureinpicture/EnterPictureInPictureEvent.idl et al.

**Comment by pliu6** [comment]
@foolip @beaufortfrancois Thanks for the reminder! I will follow up in https://bugs.webkit.org/show_bug.cgi?id=221083 and update here when it is done.

**Comment by foolip** [comment]
That's great, thanks for fixing this, @pliu6!
