### ISSUE TITLE
BikeShed nits

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/picture-in-picture#148]
Just a small thing... when talking about content attributes VS IDL attributes, make sure you use this syntax for content attributes:

```
<{element/attribute}>
```

So:

```
<{video/disablePictureInPicture}>
```

**Comment by marcoscaceres** [comment]
More details here: https://tabatkins.github.io/bikeshed/#autolink-wrappers

**Comment by beaufortfrancois** [comment]
@marcoscaceres As I'm always referring to IDL attributes, I guess we're good right?

**Comment by marcoscaceres** [comment]
Yep, if that's the case, then sure...

**Comment by marcoscaceres** [comment]
Actually, this doesn't appear to be true...

**Comment by beaufortfrancois** [comment]
Fixed with https://github.com/w3c/picture-in-picture/pull/187
