### ISSUE TITLE
Intent to Migrate: Picture-in-picture

### ISSUE THREAD

**Issue by tidoust** [w3c/picture-in-picture#150]
## Intent to Migrate: Picture-in-picture

Hi all, cc @mounirlamouri @jernoble as chairs of the Media Working Group. The recently created [Media Working Group](https://www.w3.org/media-wg/) is ready to adopt Picture-in-Picture as a W3C Recommendation track deliverable.

Note some of the sections below need some love. I let people involved in the development of this proposal chime in as needed!

### Working group decision to adopt

See the [charter of the Media Working Group](https://www.w3.org/2019/05/media-wg-charter.html#deliverables)

### Proposal

Latest [Picture-in-picture draft](https://wicg.github.io/picture-in-picture/) ([Git repo](https://github.com/WICG/picture-in-picture/))

### Summary

An API to allow websites to create a floating video window always on top of other windows so that users may continue consuming media while they interact with other content sites, or applications on their device.

### Motivation and Use Cases

Detailed in the [explainer](https://github.com/WICG/picture-in-picture/blob/master/explainer.md)

### Compatibility Risk

> Please characterize how much we might regret standardizing this new feature were we to change or remove it in the future. If you don’t have a github repository, include in this email links to relevant discussions, or documentation about support for the feature on the Web.

### Ongoing technical constraints

Implementations may start on mobile but this feature should be supported in all environments.

Some devices may only support playback of one video at a time, and may not be able to render a video overlay on top of another video.

### Link to implementation experience and demos

See [implementation status](https://github.com/WICG/picture-in-picture/blob/master/implementation-status.md)

### Data

> What data do you have available that indicates that this enhancement will affect many users of the Web. Quantify the fraction of websites that are currently using something similar to this feature. Or, if a new feature, characterize the reason that you expect this to be far reaching.

Picture-in-picture has been available on most TV sets for some time now. Several user agents have implemented a similar feature at the chrome level.

### Security and Privacy

See [responses to security and privacy questionnaire](https://github.com/WICG/picture-in-picture/blob/master/security-privacy-questionnaire.md). Also see the [Security and Privacy Considerations](https://wicg.github.io/picture-in-picture/#security-considerations) section in the latest draft

### Accessibility

Some envisioned accessibility implications that need to be reviewed further, such as the rendering of a floating video window always on top of other windows Similarly, and lack of support for captioning in the floating video.

### Internationalization

A priori no internationalization implication.

**Comment by marcoscaceres** [comment]
Just noting that the implementation status is somewhat unclear at the linked page. The intent to migrate should be clear that this is only implemented in Chrome, and that there are currently no implementation commitments from other engines (unless I missed some announcement from the WebKit team). 

Mozilla's current  position learning towards "defer" on this specification:
https://github.com/mozilla/standards-positions/issues/72 

(We are playing around with the idea of doing this without an API... but that also comes with some significant UX challenges). 

As WICG Chair this intent to migrate seems ok, though we should give people until the 17th of July to provide any additional feedback.

**Comment by domenic** [comment]
Note that (if it has multi-implementer interest) the https://wicg.github.io/picture-in-picture/#htmlvideoelement-extensions section should migrate to the HTML Standard, linking to the algorithms defined in this separate specification. This would also allow the chance to fix several issues with the current specification due to insufficient integration (e.g. the use of EventHandler attributes on HTMLMediaElement instead of GlobalEventHandlers, or the way that autoPictureInPicture, disablePictureInPicture, onenterpictureinpicture, andonleavepictureinpicture have no definitions).

**Comment by marcoscaceres** [comment]
@tidoust, all, thanks again for preparing the intent to migrate for Picture-in-picture and for the discussion. 

This specification is ready to migrate to the Media WG. However, we ask the the Media WG make an effort to move the extensions to HTML's `<video>` element to the HTML spec. 

As with the other specs migrating, be sure to update the relevant spec metadata. 

When done, kindly close this issue.

**Comment by tidoust** [comment]
Thanks @marcoscaceres, repository has now been transferred to the W3C organization and relevant info has been updated. Closing this issue accordingly.
