### ISSUE TITLE
Can  hide the play button in pip?

### ISSUE THREAD

**Issue by xiaomingtan** [w3c/picture-in-picture#151]
Because in some browsers, when the mouse leaves the PIP, the control will always exist, I need to hide the play button, NiMo Tv(https://www.nimo.tv/) is treated like this, but I don't know how he implemented it, can someone help me? Thank you

**Comment by mounirlamouri** [comment]
If the content can be play/paused, it seems fair to have the option to toggle the state. If a browser has an implementation that doesn't make sense, maybe a bug should be filed with them?

**Comment by beaufortfrancois** [comment]
I wonder if it's the same as https://github.com/GoogleChromeLabs/picture-in-picture-chrome-extension/issues/31

**Comment by xiaomingtan** [comment]
@beaufortfrancois YES，the same as GoogleChromeLabs/picture-in-picture-chrome-extension#31，chrome fix this，thank you
