### ISSUE TITLE
Integration with HTML

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/picture-in-picture#156]
In #150, @domenic wrote the following. Creating an issue so it doesn't get lost. 

> Note that (if it has multi-implementer interest) the https://wicg.github.io/picture-in-picture/#htmlvideoelement-extensions section should migrate to the HTML Standard, linking to the algorithms defined in this separate specification. This would also allow the chance to fix several issues with the current specification due to insufficient integration (e.g. the use of EventHandler attributes on HTMLMediaElement instead of GlobalEventHandlers, or the way that autoPictureInPicture, disablePictureInPicture, onenterpictureinpicture, andonleavepictureinpicture have no definitions).

**Comment by beaufortfrancois** [comment]
@mounirlamouri As we're thinking about [Candidate Recommendation](https://github.com/w3c/picture-in-picture/issues/184), what shall we do with this issue?

**Comment by marcoscaceres** [comment]
Not that I'm participating, but I'd highly encourage you to do this integration. You get a ton of stuff for free when you integrate with HTML, plus you get awesome feedback from the HTML editors.

**Comment by marcoscaceres** [comment]
(and you potentially reduce a bunch of spec duplication)

**Comment by beaufortfrancois** [comment]
@marcoscaceres I'm gonna re-open this one as I think you meant closing #148 when submitting https://github.com/w3c/picture-in-picture/pull/187

**Comment by marcoscaceres** [comment]
oh, yes, sorry about that!

**Comment by mounirlamouri** [comment]
Adding to the agenda to discuss whether the group thinks we should merge middle-size specifications like Picture-in-Picture to the HTML specification. The group agreed to move Media Playback Quality that's definitely short and it seems likely we wouldn't move large specification like MSE or EME. Where do we draw the line?

**Comment by marcoscaceres** [comment]
Note, this isn't about merging the spec back into HTML: it's about a "fair division of labor" between the two specs. I don't think the HTML folks want to maintain that picture-in-picture specific details, but anything related to `HTMLVideoElement` should really go into HTML... and HTML pointing back to this spec as needed (as per the OP).

**Comment by mounirlamouri** [comment]
I understand but if we start splitting away extensions to HTMLVideoElement from this spec, we are going to have a spaghetti specification where half of it is in the HTML spec and half in the Picture-in-Picture spec.

**Comment by marcoscaceres** [comment]
This spec already depends on all the following things defined in other specs (image below)... the thing I guess to weigh up is if anyone else would also benefit from the extensions being made to HTMLVideoElement. 
 
![Screen Shot 2020-06-17 at 9 25 05 am](https://user-images.githubusercontent.com/870154/84837862-70048880-b07c-11ea-826d-f690bee1e2a2.png)

**Comment by chrisn** [comment]
I seems to me that it's preferable for maintenance that the spec is kept in one place, so +1 to @mounirlamouri's comment above.

**Comment by tidoust** [comment]
Discussed during [11 August 2020 call](https://www.w3.org/2020/08/11-mediawg-minutes.html#t01). Two resolutions taken by the group:

**RESOLUTION:** Keep the Picture-in-Picture specification as-is as it doesn't extend the HTML specification apart from partial interface
**RESOLUTION:** Write best practices with regards to media specifications and HTML extension

**Comment by mounirlamouri** [comment]
I opened https://github.com/w3c/media-wg/issues/20 for the best practices. I will close this issue.
