### ISSUE TITLE
PR Preview broken

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/picture-in-picture#159]
@tidoust Can you reconfigure PR Preview at https://github.com/w3c/picture-in-picture/settings/installations?
We've lost it when migrating to W3C org.

**Comment by tidoust** [comment]
What exactly is broken? PR Preview is already in the list of Installed GitHub Apps and should work out of the box.

**Comment by beaufortfrancois** [comment]
I believe it should have appended the usual `Preview | Diff` text after @dontcallmedom message at  https://github.com/w3c/picture-in-picture/pull/158 but it didn't.

**Comment by beaufortfrancois** [comment]
Oh! Maybe not since it monitors `index.bs` file. See https://github.com/w3c/picture-in-picture/blob/master/.pr-preview.json

**Comment by tidoust** [comment]
Yes, for instance, #153 that you created before the transfer does not have a "PR preview" link (and shouldn't).
