### ISSUE TITLE
Describe what the autoPictureInPicture attribute means

### ISSUE THREAD

**Issue by a2sheppy** [w3c/picture-in-picture#161]
There's currently no clear explanation of what the value of the `autoPictureInPicture` attribute means, which makes it difficult to accurately implement compatibly (or document what it does). Please add a definitive explanation of what this attribute means.

I am *guessing* that it means that in addition to allowing PiP, a value of `true` for `autoPictureInPicture` causes PiP mode to automatically engage when the element is presented. If so, however, what if `disablePictureInPicture` is `true`? Can it still be autodeployed even if the user can't manually toggle it (I know, it sounds crazy, but worth being clear on this)?

If it's an autodeploy enable/disable toggle, it should be named `autoPictureInPictureDisabled` (I've filed issue #160 separately to suggest that `disablePictureInPicture` be changed to `pictureInPictureDisabled`, to align better with the other attributes throughout HTML that use "disabled" rather than "disable" when naming attributes.

Or does it reflect that PiP is currently in its automatically deployed state, rather than that autodeploy is enabled?

**Comment by beaufortfrancois** [comment]
I think https://w3c.github.io/picture-in-picture/#auto-pip and https://developers.google.com/web/updates/2019/02/chrome-73-media-updates#auto-pip cover what this attribute does.

- When document becomes hidden, the video element whose autopictureinpicture attribute was set most recently automatically enters Picture-in-Picture, if allowed.
- When document becomes visible, the video element in Picture-in-Picture automatically leaves it.

Does this help?
