### ISSUE TITLE
Add a option to go fullscreen from picture in picture window 

### ISSUE THREAD

**Issue by vignestion** [w3c/picture-in-picture#166]
"Add a fullscreen option in PIP window " is the option already available I've tried to trigger fullscreen when the user closes the pip window but obviously it is going to throw an error 
`Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.`

**Comment by beaufortfrancois** [comment]
This would be a browser feature request. As this repository is dedicated to the spec, I'll close this issue but feel free to submit one for Chromium at https://crbug.com/?q=component:Blink%3EMedia%3EPictureInPicture and we'll make sure it's triaged properly.
