### ISSUE TITLE
Style restrictions in picture-in-picture mode excludes mirrored video use cases

### ISSUE THREAD

**Issue by aburnson** [w3c/picture-in-picture#167]
One potential use case for picture-in-picture is to display one's own local video camera outside of the page window. For example, many web-based videoconferencing applications use a `<video>` element to display the local video so the user can see what they are sending. This video element is typically styled with a transform such as `transform: scaleX(-1)` in order to horizontally flip the display of the attached MediaStream. Horizontal flipping is done to achieve a more natural mirror effect.

Due to #81 and #83 styling in picture-in-picture mode is ignored, which means there is no way to achieve the mirror effect. I'm wondering whether it might make sense to allow for an exception to that rule to permit a transform that horizontally flips the video for this use case?

**Comment by beaufortfrancois** [comment]
With arbitrary HTML content in Picture-in-Picture, this won't be an issue anymore.

FYI some video conferences web apps use today the "canvas to video" trick to have this mirror effect displayed in a Picture-in-Picture window. See https://developers.google.com/web/updates/2018/10/watch-video-using-picture-in-picture#show_canvas_element_in_picture-in-picture_window

I'm gonna close this issue as there is a workaround for now.
