### ISSUE TITLE
Does pictureInPictureEnabled need to be false or can be "undefined" if the picture-in-picture support is not available?

### ISSUE THREAD

**Issue by pliu6** [w3c/picture-in-picture#170]
https://github.com/w3c/picture-in-picture/blob/4db5e801275ce740f31a3ab7615969a28894bba3/index.bs#L394

**Comment by beaufortfrancois** [comment]
`pictureInPictureEnabled` is `undefined` if Picture-in-Picture Web API is not available.
See https://developers.google.com/web/updates/2018/10/watch-video-using-picture-in-picture#feature-support

```js
if (!('pictureInPictureEnabled' in document)) {
  console.log('The Picture-in-Picture Web API is not available.');
}
else if (!document.pictureInPictureEnabled) {
  console.log('The Picture-in-Picture Web API is disabled.');
}
```
