### ISSUE TITLE
Rename CSS pseudo-class :picture-in-picture

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/picture-in-picture#172]
One way of thinking about the future of the Picture-in-Picture Web API is the ability to actually move an HTML element from a web page to a Picture-in-Picture window. In that case, the `:picture-in-picture` CSS pseudo-class name would be confusing for web developers as it would be hard to differentiate the web page element and the one in the Picture-in-Picture window.

This is why I suggest we rename the CSS pseudo-class `:picture-in-picture` to something more specific.
What do you think of `:picture-in-picture-inline`?

@jernoble @mounirlamouri @pliu6
I'm all ears if you have other ideas.

**Comment by mounirlamouri** [comment]
This LGTM. The name came from a brief early morning brainstorm between François and I so if @jernoble or @pliu6 you have a better idea, please let us know :) The intent here is to avoid painting ourselves in a corner.

**Comment by tidoust** [comment]
Discussed during the [Media WG call on 12 May 2020](https://www.w3.org/2020/05/12-mediawg-minutes.html#t01).

**Resolution:** Francois Beaufort to craft a PR to add `picture-in-picture-inline` pseudo-class (see [minutes](https://www.w3.org/2020/05/12-mediawg-minutes.html#r01))

**Comment by beaufortfrancois** [comment]
I'll do this next week!

**Comment by elopezanaya** [comment]
at some point is expected any support to set the position of the window other than down right?

**Comment by beaufortfrancois** [comment]
As the `:picture-in-picture` CSS pseudo class has been implemented in Safari now and a dedicated [WICG Document Picture-in-Picture API](https://github.com/WICG/document-picture-in-picture) has been proposed, I'm going to close this issue.
