### ISSUE TITLE
CfC: Publish FPWD of Picture-in-Picture

### ISSUE THREAD

**Issue by tidoust** [w3c/picture-in-picture#173]
This is a Call for Consensus within the Media Working Group to publish the current Editor's Draft of the [Picture-in-Picture](https://w3c.github.io/picture-in-picture/) specification as a [First Public Working Draft](https://www.w3.org/2019/Process-20190301/#first-wd) with the shortname `picture-in-picture`.

If you support the publication of this document, you may either remain silent (silence is considered consent) or voice support through 👍 or ❤️ reactions here.

If you believe it is premature to publish the document as a First Public Working Draft, please raise concerns here by the end of **January 24th 2020**, including rationale for your objection.

Publication as a First Public Working Draft does not imply that the document already represents the consensus of the Working Group. The document may still change entirely after publication. That said, publication as a First Public Working Draft triggers a first call for exclusion per the W3C Patent Policy. As such, it is always better if the document and the issues opened against it globally capture the envisioned scope. If you have comments and suggestions for new features, I encourage you to file an issue.

**Comment by mounirlamouri** [comment]
The CfC period has passed and there were no objection. GitHub reactions and silence are considered support so we will go forward with the FPWD.

**Comment by tidoust** [comment]
[FPWD of Picture-in-Picture](https://www.w3.org/TR/2020/WD-picture-in-picture-20200130/) published yesterday. Publication triggered a [call for exclusions](https://lists.w3.org/Archives/Public/public-media-wg/2020Jan/0001.html) as expected.
