### ISSUE TITLE
Add non-normative language about fullscreen/remote playback relationship

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/picture-in-picture#175]
What should happen if a video in Picture-in-Picture is sent fullscreen or played remotely? We may want to offer recommendations to implementers in the specification.

**Comment by beaufortfrancois** [comment]
I'll take care of this and send a PR shortly.

**Comment by beaufortfrancois** [comment]
@mounirlamouri I've just sent https://github.com/w3c/picture-in-picture/pull/185 to address this issue. Note that I didn't add anything to the remote playback section as I'm not sure we need to add anything.

Something like "Don't run the exit Picture-in-Picture algorithm when `pictureinPictureElement` is played remotely" does not seem that useful to me.
