### ISSUE TITLE
Multiple picture-in-picture.

### ISSUE THREAD

**Issue by kened-ferreira** [w3c/picture-in-picture#183]
It would be useful if was possible to have several simultaneous picture-in-picture windows.
Maybe one pip per tab.

**Comment by tidoust** [comment]
Doesn't the specification already cater for this?

It does assume that a given Document (which should match what you call _tab_) can only have one Picture-in-Picture window, but allows multiple pip windows for different documents, up to implementations (and underlying platforms):

> Whether only one window is allowed in Picture-in-Picture mode will be left to the implementation and the platform
> https://w3c.github.io/picture-in-picture/#one-pip-window

**Comment by beaufortfrancois** [comment]
@kened-ferreira The spec allows it. Browsers should be able to support multiple Picture-in-Picture windows.

> Operating systems with a Picture-in-Picture API usually restrict Picture-in-Picture mode to only one window. Whether only one window is allowed in Picture-in-Picture mode will be left to the implementation and the platform. 
Source: https://w3c.github.io/picture-in-picture/#one-pip-window

**Comment by kened-ferreira** [comment]
> @kened-ferreira The spec allows it. Browsers should be able to support multiple Picture-in-Picture windows.
> 
> > Operating systems with a Picture-in-Picture API usually restrict Picture-in-Picture mode to only one window. Whether only one window is allowed in Picture-in-Picture mode will be left to the implementation and the platform.
> > Source: https://w3c.github.io/picture-in-picture/#one-pip-window

Thank you!

**Comment by jimmywarting** [comment]
now with experimental arbitrary content i guess it could be useful to pop up multiple graphs of your websites analytics.
eg: one graph showing live interaction and another showing server memory or something like it.
