### ISSUE TITLE
leavepictureinpicture event should be fired with the Picture-in-Picture window 

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/picture-in-picture#188]
> Ohh... um... ok... this seems like an odd API design choice here... why not fire an `EnterPictureInPictureEvent` with "leavepictureinpicture" (yes, it has "Enter" on the front, boo!) if the developer still needs to access `pictureInPictureWindow`? Otherwise, the API forces the developer to keep an unnecessary reference to a variable in the global or some outer scope?

_Originally posted by @marcoscaceres in https://github.com/w3c/picture-in-picture/pull/149_

**Comment by beaufortfrancois** [comment]
This seems like a good suggestion to me. What do you think @mounirlamouri @jernoble?

> When the exit Picture-in-Picture algorithm is invoked, the user agent MUST run the following steps:
> 1. If pictureInPictureElement is null, throw a InvalidStateError and abort these steps.
> 1. Run the close window algorithm with the Picture-in-Picture window associated with pictureInPictureElement.
> 1. Unset pictureInPictureElement.
> 1. ~~Queue a task to fire an event with the name `leavepictureinpicture` at the video with its bubbles attribute initialized to true.~~
> 1. __Queue a task to fire an event with the name `leavepictureinpicture` using `PictureInPictureEvent` at the video with its bubbles attribute initialized to true and its `pictureInPictureWindow` attribute initialized to "Picture-in-Picture window".__

**Comment by beaufortfrancois** [comment]
For info, here's the potential spec change: https://github.com/w3c/picture-in-picture/pull/189

**Comment by mounirlamouri** [comment]
@jernoble any concern from Apple here?

**Comment by jernoble** [comment]
LGTM.
