### ISSUE TITLE
Add progress bar and allow to control it in PiP

### ISSUE THREAD

**Issue by cateyes99** [w3c/picture-in-picture#193]
It'd be very handy to have a **progress bar** and allow us to **control** it (click on and move along the bar) in **PiP**. This is very much desired, thanks 😄

**Comment by kened-ferreira** [comment]
I agree with you. Opera and Vivaldi have pip progress bar, already.

**Comment by kened-ferreira** [comment]
Yes.

**Comment by Mahdi-Noor-Hasan** [comment]
Opera and Vivaldi already has this and Firefox supports seek forward and backward from left and right arrow keys. But other chromium based browsers don't have any these features.

**Comment by beaufortfrancois** [comment]
I'm going to close this issue as it is not a spec issue.
Feel free to file bugs agains browsers implementation for this. See https://web.dev/how-to-file-a-good-bug/
