### ISSUE TITLE
Adjust Volume

### ISSUE THREAD

**Issue by KamilSzerlag** [w3c/picture-in-picture#194]
It would be nice to have an option to adjust volume and mute video by PiP.

**Comment by kened-ferreira** [comment]
Yes, that would be useful. In Opera, the pip has volume control with the mouse scroll. Also, it has the video progress bar. I don't understand why Chrome hasn't added these features to the pip yet.

**Comment by kened-ferreira** [comment]
Another useful thing would be to allow multiple simultaneous pips. Firefox Nightly has just implemented this feature.

**Comment by beaufortfrancois** [comment]
I'm going to close this issue as it is not a spec issue.
Feel free to file bugs agains browsers implementation for this. See https://web.dev/how-to-file-a-good-bug/

With that said, I wonder if a media session action for handling volume would make sense...
