### ISSUE TITLE
Default size of Picture in Picture 

### ISSUE THREAD

**Issue by vaib-saxena** [w3c/picture-in-picture#198]
Hi, 

Is it possible to change the default size of Picture in Picture window in any chromium based browser. Default size of PiP in Safari is larger than what Chromium browsers offer. 
Also, Is it essentially a browser feature?

**Comment by uoau** [comment]
I also want to change the size of the PIP window.But its max size is 440px

**Comment by beaufortfrancois** [comment]
I'm going to close this issue as it is not a spec issue.
Please file a chromium bug if not already at https://bugs.chromium.org/p/chromium/issues/entry?components=Blink%3EMedia%3EPictureInPicture so that the Chrome team can have a look.
