### ISSUE TITLE
No option to change PiP window shape

### ISSUE THREAD

**Issue by technikhil314** [w3c/picture-in-picture#201]
Thanks all for awesome efforts you folks are putting to make web a really better place for the world.

I am creating an open source app to help video creators create video right from their browser rather than going through hassle of setting up desktop apps like OBS studio or installing and keeping some browser extension.

I need ability to add background and give different shapes to PiP window. 

Do we have any of such feature in working draft or in any early stages.

I would really like `border-radius` and `clip-path` property support on `:picture-in-picture` class selector.

If you want to try out what I am building or want to get more deeper into the use case just head towards [This app](https://openrtc.vercel.app/vlog) and click on `Start recording...` button. The video you will see is an PiP video. 
Currently this works on latest version of any chromium based browser. Firefox is yet to support PiP. 

Let me know if I am missing anything here. 

Thanks.

**Comment by beaufortfrancois** [comment]
Support for different shapes of PiP windows is not planned.
