### ISSUE TITLE
PiP resize window not working on linux

### ISSUE THREAD

**Issue by CarolVilarino** [w3c/picture-in-picture#202]
**Op. System:** Debian GNU/Linux 10 (buster) 
**Browser:** Firefox 78.9.0esr (64-bit)

I can move the window but I'm not being able to resize the PiP window on Linux, 
![image](https://user-images.githubusercontent.com/44785659/114310909-e7e7e780-9ac2-11eb-874f-c0c5dc125a61.png)
![image](https://user-images.githubusercontent.com/44785659/114310936-03eb8900-9ac3-11eb-8bf7-55c7f757a9e6.png)
https://media2.giphy.com/media/ouDJe6xKYhl2oH7p0D/giphy.gif

**Comment by beaufortfrancois** [comment]
I'm going to close this issue as it is not a spec issue.
Please file a chromium bug if not already at https://bugs.chromium.org/p/chromium/issues/entry?components=Blink%3EMedia%3EPictureInPicture so that the Chrome team can have a look.
