### ISSUE TITLE
Picture in Picture with getUserMedia on iPhone Safari

### ISSUE THREAD

**Issue by virafpatrawala** [w3c/picture-in-picture#206]
I'm trying to use the Picture in Picture API with a video element receiving a getUserMedia stream. This is working well on the PC (safari and chrome) but I am getting an error on iPhone Safari:

`Unhandled Promise Rejection: NotSupportedError: The video element does not support the Picture-in-Picture mode.`

Wanted to confirm if this is just not supported, or am I making some mistake. If so, can you please suggest any work-arounds for the same?

Thanks!

**Comment by beaufortfrancois** [comment]
@jernoble may know

**Comment by eric-carlson** [comment]
Unfortunately, iOS WebKit has to block PiP for video elements backed by a MediaStream because the system doesn't allow camera capture when an application is in the background.
