### ISSUE TITLE
Clicking anywhere except on control should toggle playback

### ISSUE THREAD

**Issue by Danny8bit** [w3c/picture-in-picture#207]
I'm finding the feature a great way to watch BitChute videos, whilst working on enhancements, but it would be great if it wasn't necessary to click on the small pause / play control to toggle video playback, where just like for the main HTML5 video player, clicking anywhere on the video, except on a control, should by default toggle video playback, i.e. pause if playing, and play if paused.

**Comment by beaufortfrancois** [comment]
I'm going to close this issue as it is not a spec issue.
Feel free to file bugs agains browsers implementation for this. See https://web.dev/how-to-file-a-good-bug/
