### ISSUE TITLE
Simultaneous Video and Canvas PIP

### ISSUE THREAD

**Issue by Xaekai** [w3c/picture-in-picture#209]
The API should allow for multiple elements to share a single pip. My desired use case is a canvas overlayed atop a video to facilitate closed captions for the hearing impaired and text tracks for videos in languages foreign to the viewer.

**Comment by chrisn** [comment]
I believe that this use case would by enabled by the proposed Document Picture-in-Picture API, see https://discourse.wicg.io/t/proposal-document-picture-in-picture/5736 for details and to mention your use case there.

**Comment by Xaekai** [comment]
Thank you. I will.
