### ISSUE TITLE
Typo: Return promise vs resolve promise

### ISSUE THREAD

**Issue by joeyparrish** [w3c/picture-in-picture#226]
I believe here: https://github.com/w3c/picture-in-picture/blob/8e590950301a7379d7de1ec64c50324526280c85/index.bs#L353

> _Return_ promise ...

Should say:

> _Resolve_ promise ...

**Comment by marcoscaceres** [comment]
Agree. Further, retuning the promise should be step 1, then go in parallel, then eventually queue a task to resolve it.

**Comment by beaufortfrancois** [comment]
Thanks @joeyparrish for catching this!
I've opened https://github.com/w3c/picture-in-picture/pull/227 to address this issue.

@marcoscaceres The first sentence says `The {{requestPictureInPicture()}} method, when invoked, MUST return <a>a new promise</a> |promise| and run the following steps <a>in parallel</a>:` which I believe should be enough.
