### ISSUE TITLE
Editorial: Cross reference fixes

### ISSUE THREAD

**Issue by markafoltz** [w3c/picture-in-picture#234]
The spec refers to a _context object_, e.g.

```
The {{pictureInPictureEnabled}} attribute's getter must return `true` if
<a>Picture-in-Picture support</a> is `true` and the <a>context object</a> is
<a>allowed to use</a> the feature indicated by attribute name
`picture-in-picture`, and `false` otherwise.
```

I could not find a definition for _context object_; I think it probably means _browsing context_, as that  is an input to the [allowed to use](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#allowed-to-use) steps.

The spec also defines the term _active Picture-in-Picture session_, but does not reference it anywhere (at line 188). Was it meant to be exported?

**Comment by beaufortfrancois** [comment]
@markafoltz I've opened https://github.com/w3c/picture-in-picture/pull/235 to fix all bikeshed errors.
